# -*- coding: utf-8 -*-
"""aula 3 progamaçao em python

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O-ojx-deXjrE8o52VH2Rmw2FF5Nb5F_y
"""

#SNAKE CASE
#PALAVRAS COMPOSTAS
#DECLARAÇÕES SEMÂNTICAS

# nome_do_usuario = input('digite nome: ')
# print(nome_do_usuario)

#condatenar (,) - juntar uma variavel com um numero
# numero1 = 'r'
# numero2 = 20
# print(numero1,numero2)

#pedir para o usuario o nome a idade e a ciade e depois concatenar

# name = input('Digite seu nome:')
# age = input('Digite sua idade:')
# city = input('Digite sua cidade:')

# print('O nome do úsuario é,', name, 'sua idade é,', age, 'Ele mora na cidade:', city )

# crie um sistema que peça ao usuario o estado civil
# em seguida concatene com a seguinte frase - 'o usuario é'

#dados primitivos

# CRIE UM SISTEMA QUE SOME 2  NUMEROS

# n1 = 10
# n2 = 20
# print(n1+n2)


# print(numero1+numero2)

#CRIE UM SISTEMA QUE IMPRIMA SEU NOME NA TELA

# nome_do_usuario = input('Digite seu nome: ')
# print('Olá' , nome_do_usuario)

# CRIE UM SISTEMA QUE MULTIPLIQUE 2 NÚMEROS

# n1 = 10
# n2 = 20
# print(n1*n2)

# n1 = int(input('Digite o numero: '))
# n2 = int(input('Digite o numero: '))
# print(n1+n2)

#______________________

#SINAIS DE COMPARAÇÃO
#COMPARAR OS DADOS
#COMPARA TODOS OS DADOS PRIMITIVOS

# = ATRIBUIÇÃO
# == IGUALDADE
# * MULTIPLICAÇÃO
# + SOMA
# - SUBTRAÇÃO

# > MAIOR
# < MENOR
# <= MENOR OU IGUAL
# >= MAIOR OU IGUAL#numero1 = 'r'
# numero2 = 20
# print(numero1,numero2)

#pedir para o usuario o nome a idade e a ciade e depois concatenar

# name = input('Digite seu nome:')
# age = input('Digite sua idade:')
# city = input('Digite sua cidade:')

# print('O nome do úsuario é,', name, 'sua idade é,', age, 'Ele mora na cidade:', city )

# crie um sistema que peça ao usuario o estado civil
# em seguida concatene com a seguinte frase - 'o usuario é'

#dados primitivos

# CRIE UM SISTEMA QUE SOME 2  NUMEROS

# n1 = 10
# n2 = 20
# print(n1+n2)


# print(numero1+numero2)

#CRIE UM SISTEMA QUE IMPRIMA SEU NOME NA TELA

# nome_do_usuario = input('Digite seu nome: ')
# print('Olá' , nome_do_usuario)

# CRIE UM SISTEMA QUE MULTIPLIQUE 2 NÚMEROS

# n1 = 10
# n2 = 20
# print(n1*n2)

# n1 = int(input('Digite o numero: '))
# n2 = int(input('Digite o numero: '))
# print(n1+n2)

#______________________

#SINAIS DE COMPARAÇÃO
#COMPARAR OS DADOS
#COMPARA TODOS OS DADOS PRIMITIVOS
# != DIFERENTE

# declare uma variavel de numero inteiro e verifique se ele é maior que 10

# condicional composta

# senha_correta = '123456'
# senha_digitada = input('Digite uma senha: ')

# if senha_digitada == senha_correta:
#   print('Acesso autorizado')
# else:
#     print('Acesso Negado')

# print('Acesso ao Show.')
# idade = int(input('Digite sua idade -> '))

# if idade <=17:
#   print('Acesso negado')
# else:
#   print('Acesso autorizado')

# rua = 'rua 10'

# if rua != 'rua 10':
#    print('A festa não é na', rua)
# else:
#    print('A festa é na', rua)

# print('Vacinas para pessoas com 18 anos')
# idade = 18

# if idade != 18:
#   print('Nâo precia tomar a vacina')
# else:
#   print('Precisa se vacinar')

# n1 = int(input('digite um número -> '))
# n2 = int(input('digite um número -> '))

# if n1 > n2:
#     print('O primeiro é maoir')
# else:
#    print('O segundo é maior')

# n =10
# if n == 10:
#   print('É um 10')
# else:
#  print('Não é um 10')

# n1 = 45
# n2 = 18

# if n1>n2:
#   print('O primeiro numero é maior')

# n1 = input('Notas -> ')
# n2 = input('Notas -> ')
# n3 = input('Notas -> ')

# nome = 'Vinicius'
# sobrenome = 'Alves'
# print(nome, sobrenome)


# n1 = 200000000
# n2 = 10
# print(n1, n2)

# age = input('Digite sua idade: ')

# if age <= '17':
#   print('Não está autorizado o acesso')
# else:
#    print('Acesso autorizado você tem,', age, 'Anos')

# age = int(input('Digite sua idade -> '))

# if age >= 18 and age <= 70:
#    print('Precisa se vacinar.')
# else:
#   print('Não precisa se vacinar.')

# var1 = 123
# var2 = 'World'
# print('Hello to the {} {}'.format(var2,var1))

# var1 = 123
# var2 = 'World'
# print('Hello to the ' + var2 + str (var1))

# var1 = 'vinicius'
# var2 = 'World'
# print(f'Hello to the {var2} {var1}')

# n1 = int(input('Digite um valor -> '))
# if n1 > 0:
#   print('Número Positivo')
# elif n1 < 0:
#   print('Número Negativo')
# else:
#   print('Esse numero é 0.')


# tri1 = int(input('Digite um valor -> '))
# tri2 = int(input('Digite um valor -> '))
# tri3 = int(input('Digite um valor -> '))

# if tri1 == tri2 == tri3:
#   print('Triângulo Equilátero')
# if tri1 == tri2 != tri3:
#   print('Triângulo Isósceles')
# if tri1 != tri2 != tri3:
#   print('Triângulo Escaleno')

# texto = 'vinicius'
# comprimento = len(texto)
# print(comprimento)

# number = 100
# tipo = type(number)
# print(tipo)

# n1 = '10'
# print(type(n1))
# n2 = 15.0
# print(type(n2))
# n2 = 25
# print(type)(n3)

# v1 = int(n1)
# print(type(v1))
# v2 = str(n2)
# print(type(n2))
# v3 = int(n3)
# print(type(n3))

# palavra = 'Guarulhos'
# print(palavra)
# lista = list(palavra)
# print(lista)

# for n in range(1,8):
#   print(n)

# lista = [2,88,22]
# soma = sum(lista)
# print(soma)

# lista = [23,6,6,89,45]

# l = max(lista)
# print(l)

# n = 'abcdlpqo'
# organize = sorted(n)
# print(organize)

# for 'numero' in range(1,6):
# print(numero)

# loop for
# erve para evitar retrabalhos
# evita digitar muitas vezes

# print('Ola mundo')
# print('Ola mundo')
# print('Ola mundo')
# print('Ola mundo')
# print('Ola mundo')
# print('Ola mundo')

# for contador in range(1,11):
#   print('Ola mundo',contador)

# lista = {1,2,3,4,5,678,9,}
# for n in lista:
#      print(n)

# for n in range(1,201):
# print(n)

# menino = {
# 'key':'Vinicius',
# 'idade': 16,
# 'endereço': 'rua 10'
# }

# for a,b in menino.itens():
#   print(a,b)

# 1- Escreva um programa que use a função range() para gerar os números pares de 2 a 20 e, em seguida, imprima cada número.

# for i in range(1,11,3):
#    print(i)

# for i in range(2,21,2):
#    print(i)

# 2- Escreva um programa que use a função range() para gerar os múltiplos de 5 em 5 a 50 e, em seguida, calcule e imprima a soma desses múltiplos.

# for i in range(5,55,5):
#     print(i)

# 3- Escreva um programa que use a função type() para verificar o tipo de uma variável.

# variavel = 16
# tipo_variavel = type('variavel1')
# print(tipo_variavel)

# 4- Escreva um programa que use a função print() para imprimir uma mensagem de saudação personalizada, incluindo o nome do usuário.

# input('digite seu nome')
# print('Ola Vinicius')

# 5- Escreva um programa que use a função range() para gerar os números ímpares de 1 a 10 e, em seguida, calcule e imprima a média desses números.

# for i in range(1,11,2):
#       print('numeros impares', i)

# name = input('digite seu nome')
# hello = 'Hello'
# print(hello+' ',name)

# soma = sum(range(1,11,2))
# print(soma)

# for n in range(1,11,2):
#    print(n)

